# Generated by Django 4.2.6 on 2023-11-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=31, null=True, verbose_name='Порядок')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография')),
                ('position', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('social1', models.CharField(max_length=255, null=True, verbose_name='Ссылка1')),
                ('social2', models.CharField(max_length=255, null=True, verbose_name='Ссылка2')),
                ('info', models.CharField(max_length=255, null=True, verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['name'],
            },
        ),
    ]
