# Generated by Django 4.2.6 on 2023-12-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_teacher_options_teacher_display_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name'], 'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='display',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='order',
        ),
        migrations.AddField(
            model_name='teacher',
            name='surname',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия'),
        ),
    ]
