# Generated by Django 4.2.6 on 2024-01-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_teacher_options_remove_teacher_display_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='social1',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='social2',
        ),
        migrations.AddField(
            model_name='teacher',
            name='facebook',
            field=models.CharField(max_length=255, null=True, verbose_name='Ссылка facebook'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='instagram',
            field=models.CharField(max_length=255, null=True, verbose_name='Ссылка instagram'),
        ),
    ]
